### ISSUE TITLE
Absolute URLs start with a /

### ISSUE THREAD

**Issue by gauntface** [jekyll/jekyll-sitemap#142]
Hi,

I just tried this gem out on my site (Repo: https://github.com/gauntface/web-push-book) and the URLS start with a forward after setting a baseurl in my config:

    baseurl: https://web-push-book.gauntface.com

The end result is URLs like:

```
<url>
<loc>/https://web-push-book.gauntface.com//contributors.html</loc>
</url>
```

Is this something I'm doing wrong or have I hit a bug?

**Comment by pathawks** [comment]
You should be using `url` rather than `baseurl` for the domain:+1: 

https://byparker.com/blog/2014/clearing-up-confusion-around-baseurl/

**Comment by keegan-tennant** [comment]
Opening this again, running into an issue where using `url` allows CSS to work fine but adjusts the sitemap to use double `//` behind the domain. Changing to `baseurl` lets sitemap work as expected without doubling anything.. But any other page (besides index) breaks CSS.

**Using BASEURL**

```
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<urlset xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9 http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd">
<url>
<loc>https://keegant.com//2013/welcome-to-jekyll/</loc>
<lastmod>2013-11-10T10:18:00+00:00</lastmod>
</url>
<url>
<loc>https://keegant.com//about/</loc>
</url>
<url>
<loc>https://keegant.com//</loc>
</url>
</urlset>
```

**Using URL**

```
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<urlset xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9 http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd">
<url>
<loc>https://keegant.com/2013/welcome-to-jekyll/</loc>
<lastmod>2013-11-10T10:18:00+00:00</lastmod>
</url>
<url>
<loc>https://keegant.com/about/</loc>
</url>
<url>
<loc>https://keegant.com/</loc>
</url>
</urlset>
```

(Sitemap looks fine, but then my `/about` page shows no styling at all as its then looking for `https://keegant.com/about/assets/css/style.css` instead of `https://keegant.com/assets/css/style.css`.

Not a clue why.

**Site:** https://keegant.com
**Sitemap:** https://keegant.com/sitemap.xml (currently using baseurl to keep CSS from breaking the rest of the site).

**Comment by pathawks** [comment]
You should have an empty `baseurl` and `url` should be set to `https://keegant.com`.

If that causes strange behavior with your theme, it is your theme that needs modification.

**Comment by keegan-tennant** [comment]
@pathawks after some troubleshooting you are very right. Theme was using `baseurl` for everything by default. After about 13 commits I have the sitemap plugin working and my theme does not break.

Thank you for your suggestion. 👍
