### ISSUE TITLE
`sitemap: false` does nothing with some pages

### ISSUE THREAD

**Issue by Mikaela** [jekyll/jekyll-sitemap#75]
Hi,

I am using jekyll-sitemap with mikaela.info which is mikaela.github.io and hosted on GitHub pages.

I have multiple pages that have `sitemap: false`, but for some reason they still appear in the `sitemap.xml`.

* Appears in sitemap with `sitemap: false`, any page from https://github.com/Mikaela/mikaela.github.io/tree/master/r
* Doesn't appear in sitemap with `sitemap: false`, e.g. https://github.com/Mikaela/mikaela.github.io/blob/master/pages/channel.markdown

And the sitemap itself is https://mikaela.info/sitemap.xml .

I am totally lost on what could be the cause and any help would be appreciated.

**Comment by christerwi** [comment]
not certain, but it might have something to do with you specifying `redirects_to` in the front matter.

**Comment by Mikaela** [comment]
But shouldn't `sitemap: false` still take the highest priority?

**Comment by CrowdHailer** [comment]
I don't know if this is related but i think it might be. https://github.com/github/pages-gem/issues/139
I have a bunch of pages I moved over from tumblr is there a setting that needs to be enabled to make draft pages not show up in the site map. As mentioned I feel this should be the default behaviour because if you visit any of the draft pages as included in the sitemap you get a 404 response. Here is my sitemap http://insights.workshop14.io/sitemap.xml

**Comment by parkr** [comment]
@christerwi is correct. The sitemap has `priority :lowest` at the moment, whereas `jekyll-redirect-from` uses the default of `:normal`. Setting jekyll-redirect-from to `:lowest` and this to `:low` fixed the problem.

**Comment by pathawks** [comment]
There must be a better way.

**Comment by Mikaela** [comment]
How does one change the priority (and is it possible with GitHub pages)?

**Comment by parkr** [comment]
@Mikaela This has to be fixed in the code. If everything had the same priority, then you could just add them in a different order in your `gems` directive, but we sort them for priority on purpose. Adding new plugins requires some shuffling it looks like :/ Gross.

@benbalter would we be able to push the above change I described to GHP soonish?

**Comment by parkr** [comment]
@pathawks or @Mikaela if you have time for a PR for both for what I describe above, please submit!
