### ISSUE TITLE
[Feature request]i18n support

### ISSUE THREAD

**Issue by Glennvd** [jekyll/jekyll-sitemap#88]
Jekyll supports multilingual websites through a plugin (https://github.com/screeninteraction/jekyll-multiple-languages-plugin). It would be great to be able to include these in the sitemap as well.

**Comment by parkr** [comment]
Can you explain how you would like to include them in the sitemap? Perhaps the plugin could add them?

**Comment by pathawks** [comment]
I the deal is that [**screeninteraction/jekyll-multiple-languages-plugin**](https://github.com/screeninteraction/jekyll-multiple-languages-plugin) creates several different versions of the site: once for each language provided (generated in `_site/en/` for example), plus the default language in the root position (generated `_site/`).

Because each language is built as a separate site, the `sitemap.xml` that is built in the root cannot know about each page built for each language specific version of the site.

I have no idea how this could be addressed for this specific plugin.

**Comment by pathawks** [comment]
With the current design of **screeninteraction/jekyll-multiple-languages-plugin**, there is just no way this is possible 😞

**Comment by KMax** [comment]
There're [guidelines](https://support.google.com/webmasters/answer/2620865?hl=en) from Google about alternative language pages. I guess, the plugin could apply them to include links to alternative pages in the root sitemap.xml.

**Comment by Ryuno-Ki** [comment]
@pathawks Could you go more in detail about this?
> With the current design of screeninteraction/jekyll-multiple-languages-plugin, there is just no way this is possible 😞

What is the main issue here? I would like to look into writing a PR to address this (because I am currently working on [WeAreFairphone/landing-page](/WeAreFairphone/landing-page) which would benefit from this feature. I am wondering, on which site I would have to write a patch.

**Comment by pathawks** [comment]
@Ryuno-Ki Just to elaborate a bit:

The way [**screeninteraction/jekyll-multiple-languages-plugin**](https://github.com/screeninteraction/jekyll-multiple-languages-plugin) works is by generating the site multiple times, once for each language. This means that when (ie) the German version of a site is generating, Jekyll does not know anything about the English version of a site. When the English version of a site is generating, Jekyll does not know anything about the German version of the site. The way the plugin is implemented, there is no way for a plugin to even know that other language versions of the site _exist!_

In order for this sitemap plugin to work with that plugin, there would need to be only one `generate` performed on a site. That would require a complete redesign of how **screeninteraction/jekyll-multiple-languages-plugin** works; not just a few changes, but redesigning the foundational design. It impossible for **jekyll-sitemap** to work with the current design of **screeninteraction/jekyll-multiple-languages-plugin**.

I think, rather than trying to completely redesign that plugin, it would be easier to add a sitemap generator to **screeninteraction/jekyll-multiple-languages-plugin**.

**Comment by elnappo** [comment]
As a workaround I use [sitemapindex](https://support.google.com/webmasters/answer/75712?visit_id=1-636601537248483753-4146283988&rd=1) as `jekyll-sitemap` generates a `sitemap.xml` for every language e.g. `/sitemap.xml` and `/en/sitemap.xml`

`sitemap_index.xml`:
```
<?xml version="1.0" encoding="UTF-8"?>
<sitemapindex
    xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
    <sitemap>
        <loc>https://www.example.com/sitemap.xml</loc>
    </sitemap>
    <sitemap>
        <loc>https://www.example.com/en/sitemap.xml</loc>
    </sitemap>
</sitemapindex>
```

`robots.txt`:
```
User-agent: *
Sitemap: https://www.example.com/sitemap_index.xml
```

**Comment by pathawks** [comment]
@elnappo This is an interesting idea I hadn’t considered! Thanks for sharing
